apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
      - name: logging-service
        image: intikhab49/logging-service:v3.1
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging-service
  ports:
  - port: 5001
    targetPort: 5001