apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'web'
        static_configs:
          - targets: ['web:5000']
      - job_name: 'logging-service'
        static_configs:
          - targets: ['logging-service:5001']
